account/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # url(r'^$', 'account.views.account_view'),
    # url(r'^change_password/$', 'account.views.change_password'),
    url(r'^fun_add_view/$', 'account.views.fun_add_view'),
)

blog/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    url(r'^$', 'blog.views.posts_view'),
    url(r'^post/(?P<url>[\-\w]+)/$', 'blog.views.post_view'),
)

dshop/urls.py
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    url(r'^$', 'catalog.views.index_view'),
    url(r'^admin/settings/', 'my_admin.views.admin_settings'),
    url(r'^admin/', include('my_admin.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^catalog/', include('catalog.urls')),
    url(r'^account/', include('account.urls')),
    url(r'^cart/', include('cart.urls')),
    url(r'^orders/', include('orders.urls')),
    url(r'^redactor/', include('redactor.urls')),
    url(r'^blog/', include('blog.urls')),
    url(r'^login/', 'account.views.login_view'),
    url(r'^registration/', 'account.views.registration_view'),
    url(r'^logout/', 'account.views.logout_view'),
    url(r'^email_confirmation/', 'account.views.email_confirmation_view'),
    url(r'^redactor/', include('redactor.urls')),
    url(r'^search/', 'catalog.views.search_view'),
    url(r'', include('pages.urls')),
]

account/models.py
# coding=utf-8
from django.contrib.auth.models import AbstractUser
from django.db import models
# from catalog.models import Video

# Модифицируем поле email.
from dshop.additions import random_str

AbstractUser._meta.get_field('email')._unique = True
AbstractUser._meta.get_field('email').blank = False
AbstractUser._meta.get_field('email').default = ""
AbstractUser._meta.get_field('email').verbose_name = "E-mail"
AbstractUser._meta.get_field('first_name').blank = False
AbstractUser._meta.get_field('first_name').default = ""
AbstractUser._meta.get_field('last_name').blank = False
AbstractUser._meta.get_field('last_name').default = ""


class User(AbstractUser):
    address = models.TextField("Адрес", blank=True)
    region = models.CharField("Область", max_length=200, blank=True)
    city = models.CharField("Город", max_length=200, blank=True)
    index = models.CharField("Индекс", max_length=200, blank=True)
    phone = models.CharField("Телефон", max_length=200, blank=True)

    class Meta:
        verbose_name = "Пользователь"
        verbose_name_plural = "Пользователи"


class Fun(models.Model):
    first_name = models.CharField(verbose_name="Имя", max_length=250)
    last_name = models.CharField(verbose_name="Фамилия", max_length=250, blank=True)
    email = models.CharField(verbose_name="E-mail", max_length=250, unique=True)
    phone = models.CharField(verbose_name="Телефон", max_length=250, blank=True)
    date_create = models.DateTimeField(verbose_name="Дата подписки", auto_now_add=True, editable=False)

    class Meta:
        verbose_name = "Подписчик"
        verbose_name_plural = "Подписчики"

    def __unicode__(self):
        return self.first_name + u" : " + self.email


class EmailConfirmation(models.Model):
    user = models.ForeignKey(User, verbose_name="user")
    hash = models.CharField(verbose_name="Хеш", max_length=200, default='')
    ps = models.CharField(max_length=200, default='')

    def save(self, *args, **kwargs):
        if not self.hash:
            self.hash = random_str(20)
        super(EmailConfirmation, self).save(*args, **kwargs)

account/forms.py
# _*_ coding: utf-8 _*_
from django import forms
from models import User, Fun
from django.utils.translation import ugettext_lazy as _


class RegistrationForm(forms.ModelForm):
    password = forms.CharField(max_length=100, widget=forms.PasswordInput(), label=_(u'Пароль'))
    password_repetition = forms.CharField(max_length=100, widget=forms.PasswordInput(), label=_(u'Ещё раз'))

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']

    def clean(self):
        cleaned_data = super(RegistrationForm, self).clean()
        first_name = cleaned_data.get('first_name')
        last_name = cleaned_data.get('last_name')
        email = cleaned_data.get('email')
        password = cleaned_data.get('password')
        password_repetition = cleaned_data.get('password_repetition')

        if not first_name or not last_name or not email or not password or not password_repetition:
            raise forms.ValidationError("Заполните обязательные поля")
        elif password != password_repetition:
            self._errors["password"] = self.error_class(["Введите пароль"])
            self._errors["password_repetition"] = self.error_class(["Повторите пароль"])
            raise forms.ValidationError("Пароли не совпадают")
        else:
            try:
                User.objects.get(email=email)
                raise forms.ValidationError("Пользователь с таким email уже существует")
            except User.DoesNotExist:
                pass
        return cleaned_data


class LoginForm(forms.Form):
    login = forms.CharField(max_length=100, label=_(u'Ваш email'))
    password = forms.CharField(max_length=100, widget=forms.PasswordInput(), label=_(u'Пароль'))

    def clean(self):
        cleaned_data = super(LoginForm, self).clean()
        login = cleaned_data.get('login')
        password = cleaned_data.get('password')

        if not login or not password:
            self._errors["login"] = self.error_class(["Введите email"])
            self._errors["password"] = self.error_class(["Введите пароль"])
            raise forms.ValidationError("Заполните обязательные поля")

        return cleaned_data



class AddFunForm(forms.ModelForm):
    class Meta:
        model = Fun
        fields = ['first_name', 'last_name', 'email']

account/views.py
# _*_ coding: utf-8 _*_
from django.http import Http404
from django.shortcuts import render_to_response, HttpResponse, redirect
from django.core.context_processors import csrf
from django.contrib import auth
from django.template.loader import get_template
from django.template import Context
from models import User, EmailConfirmation
from forms import RegistrationForm, AddFunForm, LoginForm
from additions import get_email_provider
from dshop.additions import translit, random_str
from django.utils.translation import ugettext_lazy as _


def login_view(request):
    args = {
        'user': request.user,
        'form': LoginForm()
    }
    if request.GET:
        form = LoginForm(request.GET)
        if form.is_valid():
            email = request.GET['login']
            password = request.GET['password']
            next_page = request.GET.get('next', '')
            try:
                user = User.objects.get(email=email)
                user = auth.authenticate(username=user.username, password=password)
                if user is not None and user.is_active:
                    auth.login(request, user)
                    if next_page:
                        return redirect(next_page)
                    return redirect('/')
            except User.DoesNotExist:
                args['form_error'] = "Пользователя с таким email не существует!"
        args['form'] = form
        args['next_page'] = request.GET.get('next', '')
    return render_to_response("login.html", args)


def logout_view(request):
    auth.logout(request)
    return redirect("/")


def registration_view(request):
    args = {
        'form': RegistrationForm(),
        'user': request.user,
    }
    args.update(csrf(request))
    if request.POST:
        form = RegistrationForm(request.POST)
        if form.is_valid():
            new_user = form.save(commit=False)
            password = request.POST.get('password')
            new_user.username = translit(request.POST.get('first_name')) + "_" + random_str(10)
            new_user.set_password(password)
            new_user.is_active = False
            new_user.save()

            email_confirmation = EmailConfirmation(user=new_user, ps=password)
            email_confirmation.save()

            t = get_template('send_email_confirmation.html')
            html = t.render(Context({
                'user': new_user,
                'password': password,
                'email_confirmation': email_confirmation
            }))
            new_user.email_user(u"Подтверждение email", html)

            args = {}
            email_provider = get_email_provider(new_user.email.split("@")[1])
            if email_provider:
                args = {
                    'email_provider_title': _(email_provider[0]),
                    'email_provider_url': _(email_provider[1])
                }
            return render_to_response('registration_thank', args)
        args['form'] = form

    return render_to_response("registration.html", args)


def email_confirmation_view(request):
    confirmation_hash = request.GET.get('hash', '')
    confirmation_id = request.GET.get('i', '-1')
    try:
        email_confirmation = EmailConfirmation.objects.get(id=int(confirmation_id), hash=confirmation_hash)
        email_confirmation.user.is_active = True
        email_confirmation.user.save()
        user = auth.authenticate(username=email_confirmation.user.username, password=email_confirmation.ps)
        auth.login(request, user)
        email_confirmation.delete()
        return render_to_response("email_confirmation.html", {'user': request.user,})
    except EmailConfirmation.DoesNotExist:
        raise Http404


def account_view(request):
    args = {
        'user': request.user,
        'user_active': request.user.is_authenticated(),
    }
    args.update(csrf(request))
    args['error'] = False

    if request.POST:
        user = request.user

        if 'first_name' in request.POST and request.POST.get('first_name', '') != '':
            user.first_name = request.POST['first_name']
        else:
            args['error'] = True
            args['first_name_error'] = "error_field"

        if 'last_name' in request.POST and request.POST.get('last_name', '') != '':
            user.last_name = request.POST['last_name']
        else:
            args['error'] = True
            args['last_name_error'] = "error_field"

        if 'email' in request.POST and request.POST.get('email', '') != '':
            user.email = request.POST['email']
        else:
            args['error'] = True
            args['email_error'] = "error_field"

        if 'phone' in request.POST:
            user.phone = request.POST['phone']

        if args['error'] is False:
            user.save()
            return render_to_response("my_account.html", args)

    return render_to_response("my_account.html", args)


def change_password(request):
    if request.user.is_authenticated() and request.GET:

        old_password = request.GET.get('old_password', '')
        new_password = request.GET.get('new_password', '')

        if new_password:
            return HttpResponse("Новый пароль не может быть пустым")
        elif request.user.check_password(old_password):
            username = request.user.username
            request.user.set_password(new_password)
            request.user.save()
            user = auth.authenticate(username=username, password=new_password)
            if user is not None and user.is_active:
                auth.login(request, user)
            return HttpResponse("Ваш пароль изменён!")
        else:
            return HttpResponse("Старый пароль не верный!")
    else:
        return HttpResponse("Ошибка")


def fun_add_view(request):
    if request.GET:
        form = AddFunForm(request.GET)
        if form.is_valid():
            form.save()
            return HttpResponse("Спасибо! Вы подписаны на наши новости!")
        return HttpResponse("Данные введены не верно!")
    return HttpResponse("false")

account/templates/ajax_login.html
<h4>Вход в личный кабинет DaryaShop</h4>

<form class="popupBoxLoginForm" action="" style="position: relative">
    {% csrf_token %}
    <label for="id_email">Ваш e-mail</label>
    <input type="email" id="id_email" placeholder=""/>
    <label for="">Ваш пароль</label>
    <input type="password" id="id_password" placeholder=""/>
    <a href="#" class="popupBoxLoginFormVos">Регистрация</a>
    {% if error %}
    <p style="color: #ff0000; position: absolute; top: 120px; left: -30px;">{{ error }}</p>
    {% endif %}
    <a class="popupBoxBottom loginSubmit" href="#">Войти</a>
</form>

<img class="popupBoxLoginFormClose" src="/static/images/cross97.png">

account/templates/email_confirmation.html
{% extends "main.html" %}
{% load staticfiles %}

{% block content %}
<div class="ContentBox">
    <div class="ContentBoxHead">
        <h1>Подтверждение регистрации</h1>
    </div>
    <div class="ContentBoxPage">
        <p>Ваш аккаунт успешно активирован. Вы авторизованы!</p>
        <a href="/">Перейти на главную страницу</a>
	</div>
</div>
{% endblock %}

account/templates/login.html
{% extends "main.html" %}
{% load staticfiles %}

{% block content %}
<div class="ContentBox">
    <div class="ContentBoxHead">
        <h1>Вход</h1>
    </div>
    <div class="OrderBox">
        <form action="/login/{% if next_page %}?next={{ next_page }}{% endif %}" class="site_form registration_form" method="get">
            {% if form_error %}
                <ul class="errorlist nonfield"><li>{{ form_error }}</li></ul>
            {% endif %}
            {{ form.non_field_errors }}
            <table>
            {% for field in form %}
                <tr class="fieldWrapper">
                    <td>{{ field.label_tag }}</td>
                    <td>
                        {{ field }}
                        {{ field.errors }}
                    </td>
                </tr>
            {% endfor %}
            </table>
            <input type="submit" value="Войти" class="my_bottom"/>
            <a href="#" class="access_link">Забыли пароль?</a>
            <div style="clear:both;"></div>
        </form>
        <div class="left_on_form">
            <h3>Ещё не зарегистрированы на<br/> Darya-Shop?</h3>
            <a href="/registration/">Зарегистрироваться</a>
        </div>
        <div style="clear:both;"></div>
	</div>
</div>
{% endblock %}

account/templates/my_account.html
{% extends "base.html" %}
{% load catalog_menu %}


{% block content %}
<div id="left-block">
    {% catalog_menu %}
</div>
<div id="center-block" class="orders">
    <h1 class="title_h1">Оформление заказа</h1>

    {% if user_active %}
    <div class="user_information">
        <img src="/static/images/user91.png" alt="">
        <p>Вы авторизованы
            {% if user.first_name %}
            как <a href="/account/">{{ user.last_name }} {{ user.first_name }}</a>
            {% endif %}
            .Здесь вы можете обновить вашу личную информацию. Все изменения будут сохранены в вашем профиле.
        </p>
    </div>

    <form action="/account/" method="post">
        {% csrf_token %}

        <div class="form_group" style="width: 664px; border-bottom: 1px solid #eee;">
            <h3>Личные данные</h3>

            {% if error %}
                <span style="display:block; margin: 10px 0; color:#ff0000;">Заполните обязательные поля</span>
            {% endif %}

            {% if user_inform_error %}
            <span style="display:block; margin: 10px 0; color:#ff0000;">Заполните обязательные поля</span>
            {% endif %}
            <div class="form_group_item account {{ first_name_error }}">
                <label for="id_first_name">Ваше имя * </label>
                <input type="text" name="first_name" value="{{ user.first_name }}" id="id_first_name"/>
            </div>
            <div class="form_group_item account {{ last_name_error }}">
                <label for="id_last_name">Фамилия * </label>
                <input type="text" name="last_name" value="{{ user.last_name }}" id="id_last_name"/>
            </div>
            <div class="form_group_item account {{ email_error }}">
                <label for="id_email">Email * </label>
                <input type="text" name="email" value="{{ user.email }}" id="id_email"/>
            </div>
            <div class="form_group_item account {{ phone_error }}">
                <label for="id_phone">Телефон </label>
                <input type="text" name="phone" value="{{ user.phone }}" id="id_phone"/>
            </div>
            <div style="clear: both"></div>

            <div class="time-item">
                <input type="submit" style="float: right" value="Сохранть изменения" class="yellow_button account"/>
            </div>
        </div>
    </form>

    <form action="/account/change_password/" method="post">
        {% csrf_token %}
        <div class="form_group" style="width: 664px; margin-top: 10px">
            <h3>Изменить пароль</h3>

            <div class="form_group_item account">
                <label for="id_old_password">Старый пароль</label>
                <input type="password" name="old_password" id="id_old_password"/>
            </div>

            <div class="form_group_item account">
                <label for="id_new_password">Новый пароль</label>
                <input type="password" name="new_password" id="id_new_password"/>
            </div>
        </div>

        <div class="time-item">
            <input type="button" style="float: right; margin-right: 249px;" value="Изменить пароль" id="change_password" class="yellow_button account"/>
        </div>
    </form>

    <div style="clear: both"></div>


    {% else %}
     <div class="user_information">
        <p>Вы не вошли в систему - <a href="#" class="login_show">войти</a></p>
     </div>
    {% endif %}


</div>
{% endblock %}

account/templates/registration.html
{% extends "main.html" %}
{% load staticfiles %}

{% block content %}
<div class="ContentBox">
    <div class="ContentBoxHead">
        <h1>Регистрация</h1>
    </div>
    <div class="OrderBox">
        <form action="/registration/" class="site_form registration_form" method="post">
            {% csrf_token %}
            {{ form.non_field_errors }}
            <table>
            {% for field in form %}
                <tr class="fieldWrapper">
                    <td>{{ field.label_tag }}</td>
                    <td>
                        {{ field }}
                        {{ field.errors }}
                    </td>
                </tr>
            {% endfor %}
            </table>
            <input type="submit" value="Зарегистрироваться" class="my_bottom"/>
            <div style="clear:both;"></div>
        </form>
        <div class="left_on_form reg">
            <h3>Есть аккаунт на Darya-Shop?</h3>
            <a href="/login/">Войдите в систему</a>
        </div>
        <div style="clear:both;"></div>
	</div>
</div>
{% endblock %}

account/templates/registration_ready.html
<div id="popup_head">
    <a href="#">Зарегистрироваться</a>
    <span>или</span>
    <a href="#" class="popup_head_link login_show">Войти</a>
</div>

<p style="margin: 10px 0">Спасибо, вы зарегистрированы на Family Trend</p>
<p style="margin: 10px 0">Вы можете перейти в <a href="/account/">личный кабинет</a> или продолжить покупки</p>

account/templates/send_email_confirmation.html
Вы зарегистрированы на сайте: darya-shop.ru
Логин: {{ user.email }}
Пароль: {{ password }}

Для подтверждения регистрации пройдите, пожалуйста, по ссылке:
http://darya-shop.ru/email_confirmation/?i={{ email_confirmation.id }}&hash={{ email_confirmation.hash }}