blog/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    url(r'^$', 'blog.views.posts_view'),
    url(r'^post/(?P<url>[\-\w]+)/$', 'blog.views.post_view'),
)

dshop/urls.py
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    url(r'^$', 'catalog.views.index_view'),
    url(r'^admin/settings/', 'my_admin.views.admin_settings'),
    url(r'^admin/', include('my_admin.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^catalog/', include('catalog.urls')),
    url(r'^account/', include('account.urls')),
    url(r'^cart/', include('cart.urls')),
    url(r'^orders/', include('orders.urls')),
    url(r'^redactor/', include('redactor.urls')),
    url(r'^blog/', include('blog.urls')),
    url(r'^login/', 'account.views.login_view'),
    url(r'^registration/', 'account.views.registration_view'),
    url(r'^logout/', 'account.views.logout_view'),
    url(r'^email_confirmation/', 'account.views.email_confirmation_view'),
    url(r'^redactor/', include('redactor.urls')),
    url(r'^search/', 'catalog.views.search_view'),
    url(r'', include('pages.urls')),
]

my_admin/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    url(r'^upload_image/$', 'my_admin.views.video_upload'),
    url(r'^update_product_sort/$', 'my_admin.views.update_product_sort'),
    url(r'^tree_categories/(?P<id>\d+)/', 'my_admin.views.tree_categories'),
    url(r'^get_products_list/', 'my_admin.views.get_products_list'),
    url(r'^update_category_sort/', 'my_admin.views.update_category_sort'),
)

my_admin/models.py
# -*- coding: utf-8 -*-
from django.db import models


class SiteSettings(models.Model):
    site_name = models.CharField('Название сайта', max_length=200)
    description = models.CharField('Description', max_length=200)
    keywords = models.CharField('Keywords', max_length=200)

    phone = models.CharField('Телефон', max_length=200)
    email = models.CharField('E-mail', max_length=200)

    vk = models.CharField('Вк', max_length=200)
    inst = models.CharField('Instagram', max_length=200)

    head_banner = models.ImageField("Баннер (главный)", upload_to="static/uploads/", blank=True, max_length=1000)
    head_banner_a_href = models.CharField('Баннер (главный) ссылка', max_length=200, default="/", null=True)

    def save(self, *args, **kwargs):
        if self.head_banner == '':
            model = SiteSettings.objects.get(id=self.id)
            self.head_banner = model.head_banner
        super(SiteSettings, self).save(*args, **kwargs)

    class Meta:
        verbose_name = 'Настройки'
        verbose_name_plural = 'Настройки'

my_admin/forms.py
from django import forms
from models import SiteSettings

class SiteSettingsForm(forms.ModelForm):

    class Meta:
        model = SiteSettings
        fields = '__all__'

my_admin/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render_to_response, HttpResponse, Http404, redirect
from django.template.context_processors import csrf
from django.utils.encoding import smart_str
from cart.models import CartProduct
from dshop.additions import upload_file
from catalog.models import Category, Product
from models import SiteSettings
from forms import SiteSettingsForm
import simplejson as json
from simplejson.compat import StringIO


def video_upload(request):
    if request.method == 'POST' and request.user.is_authenticated():
        f = request.FILES['file']
        path = "/static/uploads/"
        url = upload_file(f, path)
        return HttpResponse(url)
    return HttpResponse("no")


def sort_list():
    mass_object = []
    roots = Category.objects.filter(parent=None, public=True)

    def rec_list(obj):
        obj.title = smart_str("— "*obj.step) + smart_str(obj.title)
        mass_object.append(obj)
        children = Category.objects.filter(parent=obj, public=True)

        for child in children:
            rec_list(child)

    for root in roots:
        rec_list(root)

    return mass_object


def tree_categories(request, id=-1):
    if request.user.is_authenticated():
        return render_to_response("tree_categories.html", {
            'categories': sort_list(),
        })
    raise Http404


def admin_settings(request):
    if request.user.is_authenticated():
        args = {}
        args.update(csrf(request))
        try:
            model = SiteSettings.objects.get(id=1)
            args['form'] = SiteSettingsForm(instance=model)
        except SiteSettings.DoesNotExist:
            args['form'] = SiteSettingsForm()

        if request.POST:
            form = SiteSettingsForm(request.POST, request.FILES)
            if form.is_valid():
                model = form.save(commit=False)
                model.id = 1
                model.save()
                return redirect('/admin/')
            else:
                args['form'] = form

        return render_to_response("admin_settings.html", args)
    else:
        return redirect('/admin/')


def get_products_list(request):
    mass_id = []

    for id in request.GET.get("mass_id", "").split(","):
        if id != "":
            mass_id.append(int(id))

    sum_all = 0

    products = []
    for product in CartProduct.objects.filter(id__in=mass_id):
        product.sum = product.cart_price * product.cart_count
        sum_all += product.cart_price * product.cart_count
        products.append(product)

    return render_to_response("get_products_list.html", {'products': products, 'sum': sum_all})


def update_product_sort(request):
    if request.user.is_authenticated() and request.GET:
        sorts = request.GET['sorts']
        for pr_id, pr_sort in json.loads(sorts).items():
            try:
                product = Product.objects.get(id=int(pr_id))
                print str(product.id) + " == " + pr_sort
                product.sort = pr_sort
                if product.save():
                    print str(product.id) + " == " + product.sort
                else:
                    print "false"
            except Product.DoesNotExist:
                pass
        return HttpResponse('ok')

    raise Http404()


def update_category_sort(request):
    if request.user.is_superuser:
        try:
            category = Category.objects.get(id=int(request.GET.get('category_id')))
            sort_type = request.GET.get('sort_type')

            if sort_type == "up":
                category_prev = None
                for root in Category.objects.filter(parent=None).order_by('sort'):
                    if category.id == root.id:
                        if category_prev:
                            category_prev.sort, category.sort = category.sort, category_prev.sort
                            category_prev.save()
                            category.save()
                        return HttpResponse(json.dumps({'error': False}))
                    category_prev = root

            if sort_type == "down":
                category_prev = None
                for root in reversed(Category.objects.filter(parent=None).order_by('sort')):
                    if category.id == root.id:
                        if category_prev:
                            category_prev.sort, category.sort = category.sort, category_prev.sort
                            category_prev.save()
                            category.save()
                        return HttpResponse(json.dumps({'error': False}))
                    category_prev = root

        except Category.DoesNotExist:
            return HttpResponse(json.dumps({'error': True}))
    raise Http404()

my_admin/templates/admin_settings.html
{% extends "admin/base_site.html" %}
{% load static %}

{% block extrahead %}{{ block.super }}
    <meta charset="UTF-8">
    <script type="text/javascript" src="/static/admin/js/jquery.js"></script>
    <script src="{% static "ajaxuploader/js/fileuploader.js" %}" ></script>
    <link href="{% static "ajaxuploader/css/fileuploader.css" %}" media="screen" rel="stylesheet" type="text/css" />
    <link href="/static/redactor/css/redactor.css" type="text/css" media="all" rel="stylesheet" />
    <link href="/static/redactor/css/django_admin.css" type="text/css" media="all" rel="stylesheet" />

    <link href="/static/redactor/css/redactor.css" type="text/css" media="all" rel="stylesheet" />
    <link href="/static/redactor/css/django_admin.css" type="text/css" media="all" rel="stylesheet" />
    <script type="text/javascript" src="/static/admin/js/core.js"></script>
    <script type="text/javascript" src="/static/admin/js/admin/RelatedObjectLookups.js"></script>
    <script type="text/javascript" src="/static/admin/js/jquery.init.js"></script>
    <script type="text/javascript" src="/static/admin/js/actions.js"></script>
    <script type="text/javascript" src="/static/redactor/jquery.redactor.init.js"></script>
    <script type="text/javascript" src="/static/redactor/redactor.js"></script>
    <script type="text/javascript" src="/static/redactor/langs/ru.js"></script>
    <style>
    .breadcrumb {
        display: none;
    }
    #product_form input[type="text"] {
        width: 450px;
    }
    </style>
{% endblock %}
{% block extrastyle %}{{ block.super }}
{% endblock %}
{% block bodyclass %}{{ opts.app_label }}-{{ opts.object_name.lower }} change-form{% endblock %}

{% block my_left_menu %}
<div class="left-nav" id="left-nav">
	<ul>
		<li>
			<a href="/admin/"><i class="icon-home"></i>Начало
			</a>
		</li>
		<li>
			<a href="/admin/accounts/user/"><i class="icon-chevron-right"></i>Accounts
			</a>
			<ul>
				<li>
					<a href="/admin/accounts/user/">Пользователи</a>
				</li>
			</ul>
		</li>
		<li>
			<a href="/admin/banners/rightbanner/"><i class="icon-chevron-right"></i>Banners
			</a>
			<ul>
				<li>
					<a href="/admin/banners/rightbanner/">Баннеры справа</a>
				</li>
				<li>
					<a href="/admin/banners/slider/">Слайдер</a>
				</li>
			</ul>
		</li>
		<li>
			<a href="/admin/catalog/category/"><i class="icon-chevron-right"></i>Catalog
			</a>
			<ul>
				<li>
					<a href="/admin/catalog/category/">Категории</a>
				</li>
				<li>
					<a href="/admin/catalog/product/">Товары</a>
				</li>
			</ul>
		</li>
		<li>
			<a href="/admin/pages/page/"><i class="icon-chevron-right"></i>Pages
			</a>
			<ul>
				<li>
					<a href="/admin/pages/page/">Страницы</a>
				</li>
			</ul>
		</li>
		<li>
			<a href="/admin/shop/typedelivery/"><i class="icon-chevron-right"></i>Shop
			</a>
			<ul>
				<li>
					<a href="/admin/shop/typedelivery/">Варианты доставки</a>
				</li>
				<li>
					<a href="/admin/shop/order/">Заказы</a>
				</li>
				<li>
					<a href="/admin/shop/clients/">Клиенты</a>
				</li>
			</ul>
		</li>
		<li>
			<a href="/admin/auth/group/"><i class="icon-lock"></i>Пользователи и группы
			</a>
			<ul>
				<li>
					<a href="/admin/auth/group/">Группы</a>
				</li>
			</ul>
		</li>
        <li class="active">
			<a href="/admin/settings/"><i class="icon-home"></i>Настройки</a>
		</li>
        <li>
			<a href="/admin/email/"><i class="icon-home"></i>Рассылка</a>
		</li>
	</ul>
</div>
{% endblock %}

{% block content %}
    <ul class="breadcrumb" style="display: block">
        <li>
            <a href="/admin/">Начало</a>
            <span class="divider">»</span>
        </li>
        <li class="active">
            Настройки
        </li>
    </ul>

    <div id="content" class="colM row-fluid">
       <h2 class="content-title">Email рассылка</h2>
       <div id="content-main" class="inner-two-columns">
       <form enctype="multipart/form-data" action="" method="post" id="product_form" class="form-horizontal">
             <div class="inner-right-column">
                <div class="box save-box">
                   <div class="submit-row clearfix">
                      <button type="submit" class="btn btn-high btn-info" name="_save">Отправить</button>
                   </div>
                </div>
             </div>
             <div class="inner-center-column">
                {% csrf_token %}
                <div class="tab-content tab-content-main">

                    <fieldset class="module aligned first ">
                        <div class="control-group form-row field-site_name ">
                            <div>
                                <div class="control-label"><label class="required" for="id_site_name">Название сайта:</label></div>
                                <div class="controls">{{ form.site_name }}</div>
                            </div>
                        </div>
                        <div class="control-group form-row field-description ">
                            <div>
                                <div class="control-label"><label class="required" for="id_description">Description:</label></div>
                                <div class="controls">{{ form.description }}</div>
                            </div>
                        </div>
                        <div class="control-group form-row field-keywords ">
                            <div>
                                <div class="control-label"><label class="required" for="id_keywords">Keywords:</label></div>
                                <div class="controls">{{ form.keywords }}</div>
                            </div>
                        </div>
                        <div class="control-group form-row field-phone ">
                            <div>
                                <div class="control-label"><label class="required" for="id_phone">Телефон:</label></div>
                                <div class="controls">{{ form.phone }}</div>
                            </div>
                        </div>
                        <div class="control-group form-row field-email ">
                            <div>
                                <div class="control-label"><label class="required" for="id_email">E-mail:</label></div>
                                <div class="controls">{{ form.email }}</div>
                            </div>
                        </div>
                        <div class="control-group form-row field-vk ">
                            <div>
                                <div class="control-label"><label class="required" for="id_vk">Вк:</label></div>
                                <div class="controls">{{ form.vk }}</div>
                            </div>
                        </div>
                        <div class="control-group form-row field-inst ">
                            <div>
                                <div class="control-label"><label class="required" for="id_inst">Instagram:</label></div>
                                <div class="controls">{{ form.inst }}</div>
                            </div>
                        </div>
                        <div class="control-group form-row field-head_banner ">
                            <div>
                                <div class="control-label"><label for="id_head_banner">Баннер (главный):</label></div>

                                <div class="controls">
                                    <div class="file-upload">{{ form.head_banner }}</div>
                                </div>
                            </div>
                        </div>
                    </fieldset>

                </div>
             </div>
          </form>
       </div>
    </div>
{% endblock %}

my_admin/templates/get_products_list.html
<table class="table-cart table-order">
	<tbody>
		<tr>
			<th colspan="2" style="text-align: left; padding-left: 10px;">Наименование товара</th>
			<th width="110px">Цена</th>
			<th width="110px">Количество</th>
			<th width="110px">Сумма</th>
		</tr>
        {% for product in products %}
		<tr class="product_item">
			<td>
				<a target="_blank" href="/catalog/product/{{ product.product.id }}/"><img src="/static/uploads/{{ product.image }}" alt="" width="60px"></a>
			</td>
			<td>
				<a target="_blank" href="/catalog/product/{{ product.product.id }}/">{{ product.name }}</a>
                <p>Цвер: {{ product.cart_color }}</p>
                <p>Размер: {{ product.cart_size }}</p>
			</td>
			<td align="center">
				{{ product.cart_price }} руб.
			</td>
			<td align="center">{{ product.cart_count }} шт.</td>
			<td align="center">
				{{ product.sum }} руб.
			</td>
		</tr>
        {% endfor %}
		<tr class="result">
			<td colspan="3" align="right" style="font-weight: bold">Итого без учёта доставки:</td>
			<td></td>
			<td align="center"><span style="font-weight: bold">{{ sum }} руб.</span></td>
		</tr>
	</tbody>
</table>

my_admin/templates/size_colors.html
<select multiple="multiple" id="id_ajax_size_colors" style="display: none;">
    {% for color in colors %}
    <option value="{{ color.id }}" {{ color.selected }}>{{ color.title }}</option>
    {% endfor %}
</select>

my_admin/templates/tree_categories.html
<option value="">---------</option>
{% for categ in categories %}
    <option value="{{ categ.id }}">{{ categ.title }}</option>
{% endfor %}